server:
  port: 8082
spring:
  application:
    name: matches-odds
  cloud:
    refresh:
      enabled: false
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:25432/matchesodds}
    username: ${DB_USER:matchesodds_user}
    password: ${DB_PASS:matchesodds_pass_123}
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 15
      minimum-idle: 5
      connection-timeout: 2000
  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}
      # for L2 cache
      timeout: 2000ms
      lettuce:
        pool:
          max-active: 8
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
#      naming:
#        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
#        format_sql: true
#        use_sql_comments: true
#        generate_statistics: true

management:
  info:
    git:
      mode: simple
  # changing the actuator listening port
  server:
    port: 8083
  endpoints:
    web:
      exposure:
        include: env,refresh,health,metrics,prometheus,loggers
  endpoint:
    env:
      # enable changing env vars
      post:
        enabled: true
      show-values: always
    health:
      show-details: always
      show-components: always
    restart:
      enabled: true
  metrics:
    distribution:
      percentiles-histogram:
        http.server.requests: true  #  Enables histogram for HTTP request metrics
    tags:
      application: ${spring.application.name}

logging:
  file:
    path: ${LOGS_PATH:/var/log/matches-odds}
  level.org.hibernate.stat: DEBUG
  level.org.hibernate.SQL: DEBUG

app:
  security:
    enabled: ${APP_SEC_ENABLED:true}
  caching:
    enabled: ${APP_CACHING_ENABLED:true}
  audit:
    execution-time:
      enabled: ${APP_AUDIT_EXEC_ENABLED:true}
  rate-limiting:
    enabled: ${APP_RATE_ENABLED:true}
    max-requests: ${APP_RATE_REQUESTS:3}
    sliding-window: ${APP_RATE_WINDOW:10}


